### ISSUE TITLE
How to get shared calendar list using caldav4j from davical?

### ISSUE THREAD

**Issue by BurcuKalkan** [caldav4j/caldav4j#107]
I created my own calendar using netbeans, caldav4j and Davical. However, I can't get shared calendar list.
I can create a calendar or an event. I can see them at Agendav. But when I share calendar to other users at Agendav, I can't get it with my netbeans code.
I want to show which user shared calendar with me.
HttpClient http = createHttpClient();
HostConfiguration hostConfig = createHostConfiguration();

PropFindMethod propfind = new PropFindMethod();
propfind.setPath(caldavCredential.home);

PropProperty propFindTag = PropertyFactory.createProperty(PropertyFactory.PROPFIND);
PropProperty aclTag = PropertyFactory.createProperty(PropertyFactory.ACL);
PropProperty propTag = new PropProperty(CalDAVConstants.NS_DAV,"D","prop");
propTag.addChild(aclTag);
propFindTag.addChild(propTag);
propfind.setPropFindRequest(propFindTag);
propfind.setDepth(0);

executeMethod(hostConfig, propfind);

Set<String> keySet = (propfind.getResponseHashtable()).keySet();
for(String key: keySet){
   CalDAVResponse response =  (propfind.getResponseHashtable()).get(key);
   String href = response.getHref();

   Ace[] aces = propfind.getAces(href);
   Enumeration enumerations = aces.enumeratePriviliges();
   while(enumerations.hasMoreElements()){
       Privilege privilege = (Privilege)enumerations.nextElement();
       System.out.println("parameter: " + privilege.getParameter());
   }
}
I try to get privileges but there is no parameter. I only want which user shared calendars with me. I can make calendar, add event but I can't access shared calendar list.

**Comment by TheAntimist** [comment]
Could you provide the version of CalDAV4j being used? Also, a request and response of the same API call.

**Comment by BurcuKalkan** [comment]
com.github.caldav4j 1.0.0-rc.2

**Comment by TheAntimist** [comment]
Could you provide the HTTP Trace / Request and response of the same?

**Comment by BurcuKalkan** [comment]
request :  
path = "/caldav.php/burcu.kalkan/"
executeMethod(hostConfig, propfind);

response: 
[responseTable.txt](https://github.com/caldav4j/caldav4j/files/3472460/responseTable.txt)
![responseTable](https://user-images.githubusercontent.com/18441333/62543375-80e24c00-b866-11e9-98e2-a3300d884fc6.jpg)

**Comment by ioggstream** [comment]
Hi, we need the whole, full http trace: request and response.

**Comment by BurcuKalkan** [comment]
When I run the application all requests and responses are at the file.

[allResponse&Request.txt](https://github.com/caldav4j/caldav4j/files/3475894/allResponse.Request.txt)

**Comment by ioggstream** [comment]
I'm not sure that's already supported.

You should probably try to make this test work:
 https://github.com/caldav4j/caldav4j/blob/24e75b30c6bb6df3f1aa81059dfd2c2997e3a8ed/src/test/java/com/github/caldav4j/methods/PropFindTest.java#L73

I'd do the following:

1- write down on a text file the HTTP request you expect to work, and test it with `curl` against your caldav server;
2- once it work, add a test to junit to mimic that behavior;
3- check if you can implement that with the actual caldav4j code.

**Comment by BurcuKalkan** [comment]
I try this code but without HttpResponse. Because HttpResponse is not supported.

**Comment by BurcuKalkan** [comment]
How does caldav4j find shared users? I want a basic question, but I'm new to it and I couldn't find anything. Where can I find this user if a user has shared his calendar with me?

**Comment by ioggstream** [comment]
@BurcuKalkan the point is the following:

1- caldav4j implements calendaring on top of CalDAV protocol;
2- ACLs and <principals> are CalDAV features and should work independently of CalDAV, see https://tools.ietf.org/html/rfc3744#section-8.1.2;
3- you should be able to issue a CalDAV ACL request via either jackrabbit or `curl` using a simple HTTP request in a text file (eg. see example in https://tools.ietf.org/html/rfc3744#section-8.1.2)

If you can make a successful ACL request using the `curl` command and a request-body similar to the one in https://tools.ietf.org/html/rfc3744#section-8.1.2 we could check how to implement this.


If you need to do ACL & co, you should take some time to read the webdav RFC and be sure that your server supports that. Consider that non all caldav servers supports all the webdav specs.

**Comment by BurcuKalkan** [comment]
Thank you very much I understood. I will try to apply what you say.

**Comment by TheAntimist** [comment]
Closing this issue, as related information seems to have been provided.
