### ISSUE TITLE
How to use FreeBusyQuery with caldav4j?

### ISSUE THREAD

**Issue by BurcuKalkan** [caldav4j/caldav4j#113]
When I apply the How to use FreeBusyQuery with caldavcollection? #86 code snippets , the response returns 200, but when I call getResposeBodyAsString (), the empty String returns. When I check the URL, the .ics file contains the FreeBusy event. 

But I couldn't use CalDAVReportMethod. does not allow because it is protected. I used instead:

CalendarCalDAVReportMethod method = new Caldav4JMethodFactory().createCalendarCalDAVReportMethod();

**Comment by ioggstream** [comment]
1- Can you please create a PR with a failing freebusy request test against baikal?
2- Can you please use the issue template for filing issues? We don't know:

  -  the server you're using 
  -  the caldav4j version
  - can't see the http trace

It's quite difficult to help you being unable to see :)

Thanks,
R.

**Comment by TheAntimist** [comment]
@BurcuKalkan That ticket has outdated snippets, will update them for the newer version as we have now moved to Apache Httpclient 4, so some API changes have been made.

**Comment by TheAntimist** [comment]
@BurcuKalkan I have added an updated example for FreeBusyQuery here: https://github.com/caldav4j/caldav4j/blob/master/src/example/org/osaf/caldav4j/example/FreeBusyQueryExample.java

Note, this is for CalDAV4j version 1.0.0-rc.2 which uses Apache HttpClient 4.x

**Comment by ioggstream** [comment]
@TheAntimist you are indeed a precious contributor of this project. Users owe you a lot! Thanks!

**Comment by TheAntimist** [comment]
Closing this issue, as commit with example has been merged.
