### ISSUE TITLE
CalendarQuery

### ISSUE THREAD

**Issue by sysmat** [caldav4j/caldav4j#125]
Is there any docs how to fetch calendars between start end end date of events

**Comment by TheAntimist** [comment]
You can refer to the Caldav RFC 4791 7.8.1 on retrieving events: https://tools.ietf.org/html/rfc4791#section-7.8.1

We have a test for this whch can also serve as a sample for you on using the library: https://github.com/caldav4j/caldav4j/blob/master/src/test/java/com/github/caldav4j/methods/CalDAVReportTest.java#L136

**Comment by sysmat** [comment]
Yes I saw the the tests, but sogo response was parsed exception, so I was wondering if I'm doing something wrong

error:
```
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
```

**Comment by TheAntimist** [comment]
Hello @sysmat,

Unfortunately, we need more data than that. Our issue template generally specifies what is required for us debug:

```Steps to reproduce the issue:

  - caldav4j version or commit
  - server name and version | url
  - link to code, including:
    
   * gists with proper highlight/indent, avoid inline code without highlight/indent
   * pull requests or git patches useful to reproduce the issue

  - link to HTTP trace (it's useful because not all servers implement ALL the specs)
```

If you can provide those it would be helpful, because as it stands, I cannot tell you much based on the exception.

**Comment by sysmat** [comment]
* dependencies
```
org.mnode.ical4j:ical4j:4.0.0-alpha6
com.github.caldav4j:caldav4j:1.0.0-rc.2
```
* ical4j.properties: `net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache`

* SOGO version **4.3.0**, it is in closed network so I can't proved URL to sogo

* code

```java
private CalendarQuery buildQuery(Date start, Date end){
        CalendarData calendarData = new CalendarData();
        Comp vcalendar = new Comp("VCALENDAR");
        vcalendar.addProp(new CalDAVProp("VERSION"));
        vcalendar.addComp(new Comp("VEVENT"));
        vcalendar.getComps().get(0).addProp(new CalDAVProp("SUMMARY"));
        vcalendar.getComps().get(0).addProp(new CalDAVProp("UID"));
        vcalendar.getComps().get(0).addProp(new CalDAVProp("DTSTART"));
        vcalendar.getComps().get(0).addProp(new CalDAVProp("DTEND"));
        vcalendar.getComps().get(0).addProp(new CalDAVProp("DURATION"));
        vcalendar.getComps().get(0).addProp(new CalDAVProp("RECURRENCE-ID"));
        vcalendar.addComp(new Comp("VTIMEZONE"));
        calendarData.setComp(vcalendar);

        CompFilter filter = new CompFilter("VCALENDAR");
        filter.getCompFilters().add(new CompFilter("VEVENT"));
        filter.getCompFilters().get(0).setTimeRange(new TimeRange(start, end));

        CalendarQuery query = new CalendarQuery();
        query.setCompFilter(filter);
        query.setCalendarDataProp(calendarData);

        return query;
    }

// snipet of fetch
CalendarQuery query = buildQuery(start, end);

HttpClient client = buildHttpClient(username, password);
HttpCalDAVReportMethod method = factory.createCalDAVReportMethod(uri, query);

HttpResponse response = client.execute(method);
System.out.println(mapInputStream(response.getEntity().getContent())); //  I get response fro sogo

Calendar calendar = method.getResponseBodyAsCalendar(response); //  Parse sogo response to calandar fail
```

* SOGO response from http client as stream:

<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><D:response><D:href>/SOGo/dav/tomaz/Calendar/personal/040000008200E00074C5B7101A82E008000000009059B235AC0FD50100000000000000001000000044E34E60C72C5545A6D6E92C72290D30.ics</D:href><D:propstat><D:prop><C:calendar-data>BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Budapest
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20200214T103156Z
LAST-MODIFIED:20200810T074532Z
DTSTAMP:20200810T074532Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:DEV
PRIORITY:5
RRULE:FREQ=WEEKLY;BYDAY=MO
EXDATE:20200113T090000Z
X-MOZ-LASTACK:20200810T074532Z
DTSTART;TZID=Europe/Budapest:20190520T100000
DTEND;TZID=Europe/Budapest:20190520T110000
CLASS:PUBLIC
SEQUENCE:2
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
DESCRIPTION:Testiram web koledar
X-MOZ-SNOOZE-TIME-1578906000000000:20200212T113251Z
X-MOZ-GENERATION:28
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
DESCRIPTION:Privzeti opis Mozilla
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DURATION
END:VALARM
ORGANIZER;CN=Alenka Starc:mailto:alenka.starc@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Klemen Pravdi&#269;;ROLE=REQ-PARTICIPANT;RSVP=
 TRUE:mailto:klemen.pravdic@arnes.si
ATTENDEE;CN=Sejna soba mala - 2. nadstropje;PARTSTAT=DECLINED;ROLE=REQ-PART
 ICIPANT:mailto:sejna2mala@arnes.si
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Toma&#382; Majerhold:mail
 to:tomaz.majerhold@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200214T103156Z
LAST-MODIFIED:20200214T103156Z
DTSTAMP:20200214T103156Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:DEV
PRIORITY:5
RECURRENCE-ID;TZID=Europe/Budapest:20190527T100000
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Marko Bona&#269;;ROLE=REQ-PARTICIPANT;RSVP=TRU
 E:mailto:marko.bonac@arnes.si
ATTENDEE;PARTSTAT=ACCEPTED;CN=klemen;ROLE=REQ-PARTICIPANT;RSVP=TRUE:mailto:
 klemen.pravdic@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Avgust Jauk;ROLE=REQ-PARTICIPANT;RSVP=TRU
 E:mailto:jauk@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Toma&#382; Majerhold;ROLE=REQ-PARTICIPANT;RSVP
 =TRUE:mailto:tomaz.majerhold@arnes.si
ATTENDEE;PARTSTAT=ACCEPTED;CN=Sejna soba mala - 2. nadstropje;ROLE=REQ-PART
 ICIPANT;RSVP=TRUE:mailto:sejna2mala@arnes.si
DTSTART;TZID=Europe/Budapest:20190528T133000
DTEND;TZID=Europe/Budapest:20190528T143000
CLASS:PUBLIC
DESCRIPTION:Marko je danes na MIZ&#352;\, zato prestavljam sestanek na jutri.\n 
 \n&#381;elimo vama predstavit\, kako smo si zamislili delovanje Oddelka za razv
 oj programske opreme.\nPrilagam &#353;e prezentacijo. \n \nLP\, Alenka
LOCATION:mala sejna
SEQUENCE:1
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
ORGANIZER;CN=Alenka Starc;SCHEDULE-STATUS=1.1:mailto:alenka.starc@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200214T103156Z
LAST-MODIFIED:20200214T103156Z
DTSTAMP:20200214T103156Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:DEV sestanek
PRIORITY:5
RECURRENCE-ID;TZID=Europe/Budapest:20190603T100000
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Toma&#382; Majerhold;ROLE=REQ-PARTICIPANT;RSVP
 =TRUE:mailto:tomaz.majerhold@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Klemen Pravdi&#269;;ROLE=REQ-PARTICIPANT;RSVP=
 TRUE:mailto:klemen.pravdic@arnes.si
ATTENDEE;PARTSTAT=ACCEPTED;CN=Sejna soba mala - 2. nadstropje;ROLE=REQ-PART
 ICIPANT;RSVP=TRUE:mailto:sejna2mala@arnes.si
DTSTART;TZID=Europe/Budapest:20190603T100000
DTEND;TZID=Europe/Budapest:20190603T110000
CLASS:PUBLIC
DESCRIPTION:Prestavili so nas v veliko sejno.
LOCATION:velika sejna
SEQUENCE:2
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
ORGANIZER;CN=Alenka Starc;SCHEDULE-STATUS=1.1:mailto:alenka.starc@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200214T103156Z
LAST-MODIFIED:20200214T103157Z
DTSTAMP:20200214T103157Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:Rezultati testiranja aplikacij - Perkona
PRIORITY:5
RECURRENCE-ID;TZID=Europe/Budapest:20190708T100000
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=mateja.smrekar@arnes.si;ROLE=REQ-PARTICIP
 ANT;RSVP=TRUE:mailto:mateja.smrekar@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Iris Govedi&#269;;ROLE=REQ-PARTICIPANT;RSVP=TR
 UE:mailto:iris.govedic@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=nejc.zupancic1@guest.arnes.si;ROLE=REQ-PA
 RTICIPANT;RSVP=TRUE:mailto:nejc.zupancic1@guest.arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN='Jakli&#269; Rok';ROLE=REQ-PARTICIPANT;RSVP=TR
 UE:mailto:rok.jaklic@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=dev@arnes.si;ROLE=REQ-PARTICIPANT;RSVP=TR
 UE:mailto:dev@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Toma&#382; Majerhold;ROLE=REQ-PARTICIPANT;RSVP
 =TRUE:mailto:tomaz.majerhold@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Klemen Pravdi&#269;;ROLE=REQ-PARTICIPANT;RSVP=
 TRUE:mailto:klemen.pravdic@arnes.si
ATTENDEE;PARTSTAT=ACCEPTED;CN=Sejna soba mala - 2. nadstropje;ROLE=REQ-PART
 ICIPANT;RSVP=TRUE:mailto:sejna2mala@arnes.si
DTSTART;TZID=Europe/Budapest:20190708T100000
DTEND;TZID=Europe/Budapest:20190708T110000
CLASS:PUBLIC
DESCRIPTION:Vabim vas na kratek sestanek\, da se pomenimo\, kako nadaljevat
 i.\nLP\, Alenka
LOCATION:mala sejna
SEQUENCE:3
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
ORGANIZER;CN=Alenka Starc;SCHEDULE-STATUS=1.1:mailto:alenka.starc@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200214T103157Z
LAST-MODIFIED:20200214T103157Z
DTSTAMP:20200214T103157Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:DEV
PRIORITY:5
RECURRENCE-ID;TZID=Europe/Budapest:20190902T100000
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=dev@arnes.si;ROLE=REQ-PARTICIPANT;RSVP=TR
 UE:mailto:dev@arnes.si
ATTENDEE;PARTSTAT=ACCEPTED;CN=Matej Vadnjal;ROLE=REQ-PARTICIPANT;RSVP=TRUE:
 mailto:matej.vadnjal@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Toma&#382; Majerhold;ROLE=REQ-PARTICIPANT;RSVP
 =TRUE:mailto:tomaz.majerhold@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Klemen Pravdi&#269;;ROLE=REQ-PARTICIPANT;RSVP=
 TRUE:mailto:klemen.pravdic@arnes.si
ATTENDEE;PARTSTAT=ACCEPTED;CN=Sejna soba mala - 2. nadstropje;ROLE=REQ-PART
 ICIPANT;RSVP=TRUE:mailto:sejna2mala@arnes.si
DTSTART;TZID=Europe/Budapest:20190902T100000
DTEND;TZID=Europe/Budapest:20190902T110000
CLASS:PUBLIC
DESCRIPTION:&#381;ivjo\, \n \nGlede na analizo ankete\, bomo ta sestanek izkoris
 tili\, da se pogovorimo o smiselnosti komentarjev. \nAvtomator se je pojav
 ljal kot mo&#382;no nadomestilo za nekatere funkcionalnosti naslednjih modulov:
 \nRegistracijo naslovnih prostorov\, urejanje povezav - APIS2\, Arnes skla
 di&#353;&#269;e\, STIS.\nMatej\, zanima nas tvoje mnenje in potencialne ideje\, kaj 
 lahko optimiziramo.\n \nLP\, Alenka\n \n
LOCATION:mala sejna
SEQUENCE:4
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
ORGANIZER;CN=Alenka Starc;SCHEDULE-STATUS=1.1:mailto:alenka.starc@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200214T103157Z
LAST-MODIFIED:20200214T103157Z
DTSTAMP:20200214T103157Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:DEV
PRIORITY:5
RECURRENCE-ID;TZID=Europe/Budapest:20191014T100000
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Iris Govedi&#269;;ROLE=REQ-PARTICIPANT;RSVP=TR
 UE:mailto:iris.govedic@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=mateja.smrekar@arnes.si;ROLE=REQ-PARTICIP
 ANT;RSVP=TRUE:mailto:mateja.smrekar@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Ingrid Mo&#382;ina Podbr&#353;&#269;ek;ROLE=REQ-PARTICIP
 ANT;RSVP=TRUE:mailto:ingrid.podbrscek@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=vodje@arnes.si;ROLE=OPT-PARTICIPANT;RSVP=
 TRUE:mailto:vodje@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Klemen Pravdi&#269;;ROLE=REQ-PARTICIPANT;RSVP=
 TRUE:mailto:klemen.pravdic@arnes.si
ATTENDEE;PARTSTAT=ACCEPTED;CN=Sejna soba mala - 2. nadstropje;ROLE=REQ-PART
 ICIPANT;RSVP=TRUE:mailto:sejna2mala@arnes.si
ATTENDEE;CN=Toma&#382; Majerhold;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT:mail
 to:tomaz.majerhold@arnes.si
DTSTART;TZID=Europe/Budapest:20191014T100000
DTEND;TZID=Europe/Budapest:20191014T110000
CLASS:PUBLIC
DESCRIPTION:Zdravo\, \n \nDEV skupina je v tem letu razvijala nov uporabni&#353;
 ki vmesnik za Arnes aplikacije. Na voljo je prva testna verzija\, ki jo je
  potrebno preverit. Vabim vas na sestanek\, da se dogovorimo glede pristop
 a dela. Vodje ste na cc\; &#269;e menite da je potrebno &#353;e koga dodati na sezna
 m testerjev. Jaz sem izbrala enako ekipo\, kot za testiranje prehoda na Pe
 rkono. \n \nKlemen je pripravil tudi page\, na katerem se bo testiranje sp
 remljalo: https://wiki.arnes.si/pages/viewpage.action?pageId=52333673.\nLP
 \, Alenka
LOCATION:velika sejna
SEQUENCE:5
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
ORGANIZER;CN=Alenka Starc;SCHEDULE-STATUS=1.1:mailto:alenka.starc@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200214T103157Z
LAST-MODIFIED:20200217T090325Z
DTSTAMP:20200214T103157Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:Testiranje Arnes aplikacij
PRIORITY:5
RECURRENCE-ID;TZID=Europe/Budapest:20191104T100000
ATTENDEE;PARTSTAT=ACCEPTED;CN=Klemen Pravdi&#269;;ROLE=REQ-PARTICIPANT;RSVP=TRUE
 :mailto:klemen.pravdic@arnes.si
ATTENDEE;CN=Sejna soba mala - 2. nadstropje;PARTSTAT=ACCEPTED;ROLE=REQ-PART
 ICIPANT:mailto:sejna2mala@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Iris Govedi&#269;;ROLE=REQ-PARTICIPANT;RSVP=TR
 UE:mailto:iris.govedic@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Ingrid Mo&#382;ina Podbr&#353;&#269;ek;ROLE=REQ-PARTICIP
 ANT;RSVP=TRUE:mailto:ingrid.podbrscek@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Rok Jakli&#269;;ROLE=REQ-PARTICIPANT;RSVP=TRUE
 :mailto:rok.jaklic@arnes.si
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Klemen Andreuzzi;ROLE=REQ-PARTICIPANT;RSV
 P=TRUE:mailto:klemen.andreuzi@arnes.si
ATTENDEE;CN=Toma&#382; Majerhold;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT:mail
 to:tomaz.majerhold@arnes.si
DTSTART;TZID=Europe/Budapest:20191104T100000
DTEND;TZID=Europe/Budapest:20191104T110000
CLASS:PUBLIC
DESCRIPTION:Vabim vas na kratek sestanek\, da preverimo rezultate testiranj
 a Angular FE. \nLP\, Alenka \n
LOCATION:mala sejna
SEQUENCE:20
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-SOGO-SEND-APPOINTMENT-NOTIFICATIONS:NO
ORGANIZER;CN=Alenka Starc:mailto:alenka.starc@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200214T103156Z
LAST-MODIFIED:20200310T071122Z
DTSTAMP:20200309T085803Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:DEV
PRIORITY:5
RECURRENCE-ID:20200224T090000Z
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Klemen Pravdi&#269;;ROLE=REQ-PARTICIPANT;RSVP=
 TRUE:mailto:klemen.pravdic@arnes.si
ATTENDEE;CN=Sejna soba mala - 2. nadstropje;PARTSTAT=DECLINED;ROLE=REQ-PART
 ICIPANT:mailto:sejna2mala@arnes.si
ATTENDEE;CN=Toma&#382; Majerhold;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT:mail
 to:tomaz.majerhold@arnes.si
X-MOZ-LASTACK:20200309T085803Z
DTSTART;TZID=Europe/Budapest:20200224T100000
DTEND;TZID=Europe/Budapest:20200224T110000
CLASS:PUBLIC
SEQUENCE:2
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
DESCRIPTION:Testiram web koledar
X-MOZ-SNOOZE-TIME-1578906000000000:20200212T113251Z
X-MOZ-GENERATION:7
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
DESCRIPTION:Privzeti opis Mozilla
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DURATION
END:VALARM
ORGANIZER;CN=Alenka Starc:mailto:alenka.starc@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200214T103156Z
LAST-MODIFIED:20200406T074626Z
DTSTAMP:20200406T074526Z
UID:040000008200E00074C5B7101A82E008000000009059B235AC0FD501000000000000000
 01000000044E34E60C72C5545A6D6E92C72290D30
SUMMARY:DEV
PRIORITY:5
RECURRENCE-ID:20200406T080000Z
ATTENDEE;PARTSTAT=NEEDS-ACTION;CN=Klemen Pravdi&#269;;ROLE=REQ-PARTICIPANT;RSVP=
 TRUE:mailto:klemen.pravdic@arnes.si
ATTENDEE;CN=Sejna soba mala - 2. nadstropje;PARTSTAT=DECLINED;ROLE=REQ-PART
 ICIPANT:mailto:sejna2mala@arnes.si
ATTENDEE;CN=Toma&#382; Majerhold;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:t
 omaz.majerhold@arnes.si
X-MOZ-LASTACK:20200406T074526Z
DTSTART;TZID=Europe/Budapest:20200406T100000
DTEND;TZID=Europe/Budapest:20200406T110000
CLASS:PUBLIC
SEQUENCE:2
TRANSP:OPAQUE
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
DESCRIPTION:Testiram web koledar
X-MOZ-SNOOZE-TIME-1578906000000000:20200212T113251Z
X-MOZ-GENERATION:10
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
DESCRIPTION:Default Mozilla Description
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DURATION
END:VALARM
ORGANIZER;CN=Alenka Starc:mailto:alenka.starc@arnes.si
END:VEVENT
END:VCALENDAR</C:calendar-data></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response><D:response><D:href>/SOGo/dav/tomaz/Calendar/personal/2D36-5E43DF80-5-6A78EA80.ics</D:href><D:propstat><D:prop><C:calendar-data>BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Belgrade
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20200212T112231Z
LAST-MODIFIED:20200810T074532Z
DTSTAMP:20200810T074532Z
UID:2D36-5E43DF80-5-6A78EA80
SUMMARY:DEV
RRULE:FREQ=WEEKLY
X-MOZ-LASTACK:20200810T074532Z
DTSTART;TZID=Europe/Belgrade:20200217T100000
DTEND;TZID=Europe/Belgrade:20200217T110000
CLASS:PUBLIC
TRANSP:OPAQUE
SEQUENCE:1
X-MOZ-GENERATION:27
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
DESCRIPTION:Privzeti opis Mozilla
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DURATION
END:VALARM
ORGANIZER;CN=sejna2mala:mailto:sejna2mala@arnes.si
ATTENDEE;CN=Klemen Pravdi&#269;;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:kl
 emen.pravdic@arnes.si
ATTENDEE;CN=Alenka Starc;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:alen
 ka.starc@arnes.si
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=Toma&#382; Majerhold:mail
 to:tomaz.majerhold@arnes.si
END:VEVENT
BEGIN:VEVENT
CREATED:20200212T112231Z
LAST-MODIFIED:20200406T074640Z
DTSTAMP:20200406T074526Z
UID:2D36-5E43DF80-5-6A78EA80
SUMMARY:DEV
RECURRENCE-ID:20200406T080000Z
ATTENDEE;CN=Klemen Pravdi&#269;;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:kl
 emen.pravdic@arnes.si
ATTENDEE;CN=Alenka Starc;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:alen
 ka.starc@arnes.si
ATTENDEE;CN=Toma&#382; Majerhold;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:t
 omaz.majerhold@arnes.si
X-MOZ-LASTACK:20200406T074526Z
DTSTART;TZID=Europe/Belgrade:20200406T100000
DTEND;TZID=Europe/Belgrade:20200406T110000
CLASS:PUBLIC
TRANSP:OPAQUE
SEQUENCE:1
X-MOZ-GENERATION:9
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
DESCRIPTION:Default Mozilla Description
X-LIC-ERROR;X-LIC-ERRORTYPE=PARAMETER-VALUE-PARSE-ERROR:Got a VALUE paramet
 er with an illegal type for property: VALUE=DURATION
END:VALARM
ORGANIZER;CN=sejna2mala:mailto:sejna2mala@arnes.si
END:VEVENT
END:VCALENDAR</C:calendar-data></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>

**Comment by TheAntimist** [comment]
Thanks @sysmat I can see your issue. It's the `System.out.println`:
```HttpResponse response = client.execute(method);
System.out.println(mapInputStream(response.getEntity().getContent())); //  I get response fro sogo

Calendar calendar = method.getResponseBodyAsCalendar(response); //  Parse sogo response to calandar fail```

If you remove it, it will work. The reason is that the HttpEntity can only be read once from the stream, and so because you are reading it once for logging and another for the calendar. That's causing the issue.

Similarly one of our tests were also failing because of this. Refer #121

**Comment by sysmat** [comment]
This step `System.out.println(mapInputStream(response.getEntity().getContent()));` was just to show response from SOGO, even if I remove it I still got error:

```
Exception in thread "main" java.io.IOException: Error parsing calendar from response
	at com.github.caldav4j.methods.HttpCalDAVReportMethod.getResponseBodyAsCalendar(HttpCalDAVReportMethod.java:149)
	at si.arnes.sogo.service.SogoService.fetch(SogoService.java:69)
	at si.arnes.sogo.TomazPersonalCalQuery.main(TomazPersonalCalQuery.java:29)
Caused by: net.fortuna.ical4j.data.ParserException: Error at line 1:Expected [BEGIN], read [<?xml version]
	at net.fortuna.ical4j.data.CalendarParserImpl.assertToken(CalendarParserImpl.java:504)
	at net.fortuna.ical4j.data.CalendarParserImpl.parseCalendarList(CalendarParserImpl.java:172)
	at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:147)
	at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:184)


```

**Comment by TheAntimist** [comment]
The `getResponseBodyAsCalendar` expects the response body to contain the calendar object. But, since the response is a multistatus Xml, you can get the Multistatus object like so:
```
method.getResponseBodyAsMultiStatus(httpResponse)
```
Then, to iterate over each of them you can do this:
```
for (MultiStatusResponse response : responses) {
// do something with individual response.
}
```

Another option is also to use something like this from our [test](https://github.com/caldav4j/caldav4j/blob/6c7df0b1ba07a148614ec633afb7831aae47d936/src/test/java/com/github/caldav4j/methods/CalDAVReportTest.java#L157):

```
Collection<DavProperty> calendars = calDAVReportMethod.getDavProperties(response, CalDAVConstants.DNAME_CALENDAR_DATA);

ComponentList<VEvent> templist = new ComponentList<>();
for(DavProperty property: calendars){
        templist.addAll(CalendarDataProperty.getCalendarfromProperty(property).getComponents(Component.VEVENT));
}
```

**Comment by sysmat** [comment]
@TheAntimist thx
