### ISSUE TITLE
Upgrade use of Slide to Jackrabbit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [caldav4j/caldav4j#13]
```
The Slide project has been retired:
http://jakarta.apache.org/slide/

We should upgrade to Jackrabbit WebDAV Library 1.4:
http://jackrabbit.apache.org/jackrabbit-webdav-library.html
http://repo1.maven.org/maven2/org/apache/jackrabbit/jackrabbit-webdav/1.4/

```

Original issue reported on code.google.com by `markhob...@gmail.com` on 3 Sep 2008 at 4:07

**Comment by TheAntimist** [comment]
Anybody, know the current status of this issue, along with that what about merging the caldav4j-jackrabbit branch?

**Comment by ioggstream** [comment]
Hi @TheAntimist,

I'd really like to drop slide, but as of my last findings https://wiki.apache.org/jackrabbit/WebDAV
slide was the only webdav client library supporting ACLs. 

Moving to jackrabbit means either dropping or implement al caldav4j ACL support.

If you want to try the merge I'm willing to help.

**Comment by TheAntimist** [comment]
I just checked, and according to https://jackrabbit.apache.org/jcr/components/jackrabbit-webdav-library.html
RFC 3744 (Access Control Protocol) has been implemented. Not sure, till what extent, though.

I might try to to merge, if jackrabbit implements ACL's completely, will ask your help when necessary. Thanks for letting me know.

**Comment by ioggstream** [comment]
@TheAntimist that's great to know. 

Just fork the project and start running the tests against a caldav-compliant server. Once the tests work let  me know and I'll do my best to support you.

Thx++,
R.

**Comment by TheAntimist** [comment]
Alright, just that, I haven't gotten used to the CalDAV4j codebase yet, would like to work on that first, and then work on the jackrabbit-webddav integration. Also, would there be a more direct mode of communication to you in case, I want to contact you? Or does this work for you?

**Comment by ioggstream** [comment]
@TheAntimist here or on irc.freenode.net#calda4j

**Comment by TheAntimist** [comment]
@ioggstream Alright, thanks I'll get back to you soon.

**Comment by TheAntimist** [comment]
@ioggstream Got a bit of trouble compiling using maven 3, the repositories, you've placed in the pom.xml seem to point to addresses which seem to not exist, specifically this one: http://m2.modularity.net.au/releases and also, you seem to be using a local Repo any possibility of using the Maven Central or something.

Any other repositories, I could add, for the dependencies?

**Comment by TheAntimist** [comment]
@ioggstream Got a bit of trouble compiling using maven 3, the repositories, you've placed in the pom.xml seem to point to addresses which seem to not exist, specifically this one: http://m2.modularity.net.au/releases

Any other repositories, I could add, for the dependencies?

**Comment by ioggstream** [comment]
@TheAntimist It seems that ehcache 2.5.2 can't be downloaded anymore.

You can try:

 - http://repo1.maven.org/maven2/
 - ehcache 2.10.2

Ehcache has changed its interface, so I found this compilation issue

```
[ERROR] /home/rpolli/workspace-luna/caldav4j/src/test/java/org/osaf/caldav4j/CalDAVCalendarCollectionWithCacheTest.java:[64,9] error: CalDAVCalendarCollectionWithCacheTest.TestingCacheEventListener is not abstract and does not override abstract method notifyRemoveAll(Ehcache) in CacheEventListener
```

It should be something easy to manager though...

**Comment by TheAntimist** [comment]
@ioggstream Got the ehcache 2.10.2 and made some dummy methods to fit the CacheEventListener interface, which now makes all the code compile with the following 

	public void notifyElementEvicted(Ehcache cache, Element element) {
	}
	public void notifyRemoveAll(Ehcache cache) {
	}
	public Object clone(){
		return (Object) (new TestingCacheEventListener());
	}

But I still get the following error in lots of files during the running of the Tests in the surefire-reports

    java.lang.NoClassDefFoundError: Could not initialize class net.fortuna.ical4j.util.CompatibilityHints

Still, not sure what's going wrong. :(

**Comment by ioggstream** [comment]
Can you please link  your caldav4j fork so I can test the code?

Thx++,
R.

**Comment by TheAntimist** [comment]
@ioggstream Here's the link: https://github.com/TheAntimist/caldav4j

Also, just a note that the test errors could be due to the Artifact I downloaded did get corrupted. Like every time I try updating, I get `Non-Parseable POM for ical4j-1.0.3` and even on 1.0.5

**Comment by ioggstream** [comment]
Looking. ..
Il 29/apr/2016 22:31, "Ankush Mishra" <notifications@github.com> ha scritto:

**Comment by ioggstream** [comment]
@TheAntimist Testing your build with davical I got issues only on ACL and FreeBusy... Not bad it seems.


```
java -version
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

# mvn clean package
Failed tests:   testAddRemoveCalendarResource(org.osaf.caldav4j.google.methods.GooglePutGetTest): Response status expected:<201> but was:<404>
  createNewDocument(org.osaf.caldav4j.model.request.FreeBusyQueryTest): createNewDocument expected:<... encoding="UTF-16"?>[
  testGetCalendarByPath(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest)
  testGetEventResources(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest): expected:<0> but was:<1>

Tests in error: 
  getFolderAces(org.osaf.caldav4j.ACLCalDAVCollectionTest): Error gettinh ACLs. PROPFIND status is: -1
  getResourceAces(org.osaf.caldav4j.ACLCalDAVCollectionTest): Error gettinh ACLs. PROPFIND status is: -1
  testGetOptions(org.osaf.caldav4j.CalDAVCollectionAceTest)

Tests run: 65, Failures: 4, Errors: 3, Skipped: 21
```

**Comment by TheAntimist** [comment]
@ioggstream Looks like it's a problem on my side, because I still get the ical4j nocalssdef exception. I guess, it's an artifact issue after all. Sigh. I'll check it tomorrow, too tired for today.

**Comment by TheAntimist** [comment]
@ioggstream Phew got it to work. I found my problem was with a dependency of ical4j, which had a corrupt artifact due to as stated earlier: http://m2.modularity.net.au/releases

Here's the errors, I get pretty much similar to yours, plus some because I didn't realize that hub.chandlerproject.org doesn't exist now. Plus, your Free Busy tests. Though, since I notice you've used davical instead of chandlerproject, which seems to be defunct. I don't have the other errors. Here's my errors:

    Results :

    Failed tests:   createNewDocument(org.osaf.caldav4j.model.request.FreeBusyQueryTest): createNewDocument expected:<... encoding="UTF-16"?>[
      testAddRemoveCalendarResource(org.osaf.caldav4j.google.methods.GooglePutGetTest): Response status expected:<201> but was:<404>

    Tests in error: 
      testGetOptions(org.osaf.caldav4j.CalDAVCollectionAceTest): hub.chandlerproject.org
      testGetOptions(org.osaf.caldav4j.CalDAVCalendarCollectionTest): hub.chandlerproject.org
      testGetCalendar(org.osaf.caldav4j.CalDAVCalendarCollectionTest): hub.chandlerproject.org
      testGetCalendarByPath(org.osaf.caldav4j.CalDAVCalendarCollectionTest): hub.chandlerproject.org
      testGetEventResources(org.osaf.caldav4j.CalDAVCalendarCollectionTest): hub.chandlerproject.org
      testAddNewRemove(org.osaf.caldav4j.CalDAVCalendarCollectionTest): hub.chandlerproject.org
      testUpdateEvent(org.osaf.caldav4j.CalDAVCalendarCollectionTest): hub.chandlerproject.org
      testMultigetCalendar(org.osaf.caldav4j.CalDAVCalendarCollectionTest): hub.chandlerproject.org
      getFolderAces(org.osaf.caldav4j.ACLCalDAVCollectionTest): hub.chandlerproject.org
      getResourceAces(org.osaf.caldav4j.ACLCalDAVCollectionTest): hub.chandlerproject.org
      testCacheGetsHit(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest): hub.chandlerproject.org
      testGetCalendar(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest): hub.chandlerproject.org
      testGetCalendarByPath(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest): hub.chandlerproject.org
      testGetEventResources(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest): hub.chandlerproject.org
      testAddNewRemove(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest): hub.chandlerproject.org
      testUpdateEvent(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest): hub.chandlerproject.org
      testFun(org.osaf.caldav4j.FunTest): hub.chandlerproject.org

**Comment by ioggstream** [comment]
1- configure the GooglePutGetTest to use a google calendar account

```

  testAddRemoveCalendarResource(org.osaf.caldav4j.google.methods.GooglePutGetTest):
Response status expected:<201> but was:<404>

```

2- for the others, you should point to a caldav server (use whatever you
have instead of chandler) and let me know the results.

**Comment by TheAntimist** [comment]
@ioggstream Just an update it seems that Google has changed their Location URL for CalDAV, because they switched to OAuth, for authentication. Read more here on this issue: https://blog.mozilla.org/calendar/2013/09/google-is-changing-the-location-url-of-their-caldav-calendars/ and for using them now, you need to use this guide from google, for using their developer API's: https://developers.google.com/google-apps/calendar/caldav/v2/guide

Thus, that test won't work, if I just put in my credentials, there.

Other than that, still working on the rest.

**Comment by ioggstream** [comment]
2016-05-01 14:13 GMT+02:00 Ankush Mishra <notifications@github.com>:

> Google has changed their Location URL for CalDAV,


For now we can just ignore Google stuff unless you need it, OK?

PS: Which caldav server are you using?

**Comment by TheAntimist** [comment]
@ioggstream Finally, got my CalDAV server working. Used DAViCal, since it seemed to be not too complicated but good enough to work against, plus uses SabreDAV. Now, here's my errors:

    Failed tests:   createNewDocument(org.osaf.caldav4j.model.request.FreeBusyQueryTest): createNewDocument expected:<... encoding="UTF-16"?>[
      testGetCalendarByPath(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest)
      testGetEventResources(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest): expected:<0> but was:<1>
      testCacheGetsHit(org.osaf.caldav4j.CalDAVCalendarCollectionWithCacheTest)
      testAddRemoveCalendarResource(org.osaf.caldav4j.google.methods.GooglePutGetTest): Response status expected:<201> but was:<404>

    Tests in error: 
      testGetOptions(org.osaf.caldav4j.CalDAVCollectionAceTest

    Tests run: 65, Failures: 5, Errors: 1, Skipped: 21

Of which, one of them is the Google error of course.

**Comment by ioggstream** [comment]
Hi, I refactored your code a bit, see fix-pom-ehcache-ical4j

  1- squashed all pom.xml modification, used ${user.home} variable, ...
  2- added a caldav4jUri in CaldavCredential

Now you should be able to point to a server without editing files: 

   mvn clean package -Dcaldav4jUri=https://user:password@host/caldav.php/user/

**Comment by TheAntimist** [comment]
A bit of a late reply, worked on understanding the code for a bit, and a bit busy here and there. Anyway, I just updated the my fork, with the fix to CalDAVCollectionAceTest, also an update for CalDAVCalendarCollectionBase.allows(), which used a regex which didn't work. Found here: 689fffb5ec4c18ee26f6a2bbe7aa569c5d7ab7e5

**Comment by ioggstream** [comment]
Hi @TheAntimist 

I looked at your commits and they seem ok: I'm going to merge some of them.

  - slf4j: I think it's time to move;
  - FB query: ok, but probably depends on the server response adding a newline after <xml>;

For different errors (eg. the floating tz one) please open new tickets!

About ical4j-connector and caldav4j: I don't know very much ical4j-connector, but ical4j is a good project. 
We use caldav4j for the ability to create complex queries using sql-like syntax and the built-in cache support. All this moves code outside from your application.

Let me know if you have further questions and thanks for the good work!

**Comment by TheAntimist** [comment]
@ioggstream Thanks for the response. 

With respect to FB query, we could have a function which preprocesses spaces and so on, which sort of normalizes both. But yes, it is entirely server dependent. For Floating TZ one, I'll probably open a new ticket, soon.

Also, thanks for the review on ical4j-connector.

Addressing the Migration, issue finally, having checked some of the code on the caldav4j-jackrabbit branch, till what extent are the methods migrated? They seem ready on that side. Anything specific, do I have to work on, or just work on an extension of that branch in my fork?

**Comment by ioggstream** [comment]
@TheAntimist I merged your changes into https://github.com/caldav4j/caldav4j/commit/a7c64c71819434f75267f320c99c73413127a86a 

About jackrabbit: 

  - the basic methods (PUT, GET, DELETE) should work;
  - the xml search related methods needs to be checked;
  - ACL methods should be rewritten entirely as the class hierarchy is probably very different from the slide one.

**Comment by TheAntimist** [comment]
@ioggstream Alright, thanks. I'll see what I can do, though I expect the migration may be completed partially depending, on my requirement. But anyway, I'll give it a try.

One, last thing, can I refer to the caldav4j-jackrabbit branch here: https://github.com/caldav4j/caldav4j/tree/caldav4j-jackrabbit
while migration?

**Comment by ioggstream** [comment]
@TheAntimist:

  - Every good work of software starts by scratching a developer's personal itch (E.S. Raymond, The Cathedral and the Bazaar); 
  -  the jackrabbit branch should contain working PUT/GET/DELETE stuff: I suggest trying to merge your changes there as a starting point;

**Comment by TheAntimist** [comment]
@ioggstream Alright, thanks.  I'll see what I can come up with. :smile:

**Comment by TheAntimist** [comment]
@ioggstream I have question with respect to MkCalendarMethod. In the caldav-jackrabbit branch [MkCalendarMethod, line 61](https://github.com/caldav4j/caldav4j/blob/caldav4j-jackrabbit/src/main/java/org/osaf/caldav4j/methods/MkCalendarMethod.java#L58), in function addRequestHeaders, there's a comment which states:

       //first add headers generate RequestEntity or 
       //addContentLengthRequestHeader() will mess up things > result "400 Bad Request"
       //can not override generateRequestBody(), because called to often

But upon running, all the tests in MkCalendarTest, without the overridden MkCalendarMethod.addRequestHeaders, it works just fine. No sign of a "400 Bad Request" anywhere? Any clue, why this was specifically done?

I have updated fork with, the following, with working methods and their tests.

 - Put, implements httpclient method. Tested, already works, no changes to make.
 - Post, implements httpclient method. Already tested, should work.
 - Options, changed to jcr. Tested works.
 - Get, changed to jcr. Tested works.
 - Delete, changed to jcr. Tested works.
 - MkCalendarMethod, changed to jcr. Tested Works.

**Comment by ioggstream** [comment]
@TheAntimist maybe it's time to split-up this ticket with sub-tickets ; )

1- comments on error 400 may be tied to the caldav server implementation.
2- tickets: does davical implement them? If they work is fine anyway.
3- please open tickets for the rest.

**Comment by TheAntimist** [comment]
@ioggstream The tickets, work fine, on davical, mkticket and delticket. 

For the rest, well, not entirely sure, for what the ticket would be, because it seems to be a bit of specific thing to migrate in caldav4j, to jackrabbit.

**Comment by TheAntimist** [comment]
@ioggstream With respect to PropFindMethod, I want to ask, why has the whole class overridden, just for ticketdiscovery? Including a whole initResponseHashtable, function? I am wondering on how to proceed in this case, I could simply just override and DavMethodBase, and the except for a couple of a things most of the reponses and rest would use the jcr classes.

**Comment by ioggstream** [comment]
@TheAntimist about `org.osaf.caldav4j.model.util.PropertyFactory`:

 - exists in all branches;
 - it's an utility to avoid creating manually a lot of xml documents;
 - if the DavPropertyName supports the creation of  the xml docs required to manage ACL you can get rid of the PropertyFactory.

The more the code is clean, the better.

**Comment by TheAntimist** [comment]
@ioggstream DavPropertyName, has this function: public Element toXml(Document document)

So, I am assuming yes.

**Comment by ioggstream** [comment]
This is moved to different tickets
