### ISSUE TITLE
Bump source version to 1.7?

### ISSUE THREAD

**Issue by stefan-reich** [caldav4j/caldav4j#147]
Seems about time... I needed to change it from 1.6 in pom.xml in order to compile at all.

          <configuration>
            <source>1.7</source>
            <target>1.7</target>
          </configuration>

**Comment by ioggstream** [comment]
@TheAntimist WDYT? @stefan-reich can you pls send a PR so that we can check the CI?

**Comment by stefan-reich** [comment]
Oh... nevermind, it's actually at 1.8 already. Just in the release it's still in 1.6. So my suggestion is to make a new release I guess...

Cheers (caldav4j working great for me BTW, turned it into a fat jar as I don't use maven)

**Comment by TheAntimist** [comment]
@ioggstream This was done about 2 years ago when we bumped the version of iCal4j to 3.0.1 here: https://github.com/caldav4j/caldav4j/commit/c7a7e64f5f8a85f6bf468d69d4895924a48fbb5e .

@stefan-reich Yes this was pushed as version [1.0.0-rc.2](https://github.com/caldav4j/caldav4j/releases/tag/1.0.0-rc.2) to maven central. So depends on the version you are using.

**Comment by stefan-reich** [comment]
Yes I was using 0.9.2 as this is listed as "latest release" on your GitHub
