### ISSUE TITLE
Creating a calendar in Radicale

### ISSUE THREAD

**Issue by stefan-reich** [caldav4j/caldav4j#148]
Sorry for abusing this as a support forum (is there one somewhere else?).

I am connecting to Radicale through caldav4j, but there are 0 calendars returned by CalDAVCollection.queryCalendars(), and I am unsure how to create a calendar to put events in it. (Radicale's web interface doesn't allow creating any objects besides the collection itself.)

**Comment by ioggstream** [comment]
Try to create a CI pipeline using `radicale` so that we can reproduce the issue.

**Comment by TheAntimist** [comment]
I also recommend that you check the debug / trace logs. We use sl4j, so any connector to it would work.

**Comment by stefan-reich** [comment]
> I also recommend that you check the debug / trace logs. We use sl4j, so any connector to it would work.

I'm sorry, I don't understand. I am asking how to perform an action. Are you saying that there should always be calendars returned by queryCalendars without me doing anything?

**Comment by stefan-reich** [comment]
> Try to create a CI pipeline using `radicale` so that we can reproduce the issue.

I don't know how to create CI pipelines

**Comment by TheAntimist** [comment]
> > I also recommend that you check the debug / trace logs. We use sl4j, so any connector to it would work.
> 
> I'm sorry, I don't understand. I am asking how to perform an action. Are you saying that there should always be calendars returned by queryCalendars without me doing anything?

Apologies for the delay, given the holiday season been a bit busy. Back to topic, I meant that you can log4j as dependency for example: https://github.com/caldav4j/caldav4j/blob/master/pom.xml#L66

Then add a basic logging config like so: https://github.com/caldav4j/caldav4j/blob/master/src/test/resources/log4j2.xml

This will allow you to check all the logs that the application is generating. If you can provide that data, we could check and maybe help you out.

**Comment by ioggstream** [comment]
closing as stale
