### ISSUE TITLE
Is there a JAR file I could use?

### ISSUE THREAD

**Issue by artknight** [caldav4j/caldav4j#160]
I would like to use just the .JAR file if possible. Could any one tell me how to compile it w/out maven?

Thank you,

**Comment by TheAntimist** [comment]
You can download them from Maven Central Repository through maven. Or if you still insist on the JAR, you can download them from one of the online maven central caches here - https://search.maven.org/artifact/com.github.caldav4j/caldav4j/1.0.5/jar
