### ISSUE TITLE
Fix CalDAVCollectionTest.queryPartialCalendar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [caldav4j/caldav4j#48]
```
Test currently fails - it appears that the recurring event is not being 
expanded.  Could be a problem with Cosmo, needs investigation.
```

Original issue reported on code.google.com by `markhob...@gmail.com` on 18 Feb 2011 at 2:10

**Comment by TheAntimist** [comment]
@ioggstream Been debugging, got down to the root of the problem. Two problems, specifically:

in getCalDAVResources, there's this condition here:

		if (usingCache) {
			query.setCalendarDataProp(null);
			log.debug("Using cache, so I am removing calendar data");
		}

which disables the CalendarData.EXPAND from happening. So, the expand doesn't set, thus, only one VEVENT is returned.

Second thing, is that after expansion in into multiple VEVENTS, you can still have one VCALENDAR, which is what I get in DAViCal. Thus, either you'd need to parse each VEVENT separately as a calendar.

Should I just remove the ``setCalendarDataProp(null)``? or even remove the test?

**Comment by ioggstream** [comment]
I need some time to investigate the reason of that part. You can skip the
test for now but we need to add a set of performance test to check the
overhead of removing the setCalendarDataProp (null).

**Comment by TheAntimist** [comment]
Alright, going ahead with Ignoring it for future reference.

**Comment by TheAntimist** [comment]
Closing this since, we know the reason, but have no reason to fix.
