### ISSUE TITLE
Publish artifact onto Maven Central

### ISSUE THREAD

**Issue by GoogleCodeExporter** [caldav4j/caldav4j#55]
```
Suggest to publish the next release of caldav4j onto Maven Central.  Since you 
will hopefully be on Jackrabbit for the 0.8 release, all dependent artifacts at 
that point will be in Maven Central.
```

Original issue reported on code.google.com by `jameswen...@gmail.com` on 23 Aug 2013 at 5:39

**Comment by artheus** [comment]
Is there a PGP key that should be used for this project? I would like to put it up to Maven Central, but don't know how you want to do with PGP signatures.
Should I just go ahead and create a PGP key for this, or is there one that should be used for this?

**Comment by ioggstream** [comment]
@artheus Go on with your keys. I used to use google-code but it's dismantled now... Let me know and again sorry for the delay :(

**Comment by TheAntimist** [comment]
@ioggstream Any update on whether this ever happened?

**Comment by ioggstream** [comment]
It seems we should use com.github.caldav4j  or something similar https://issues.sonatype.org/browse/OSSRH-22325

**Comment by TheAntimist** [comment]
@ioggstream Since, OSAF seems to be defunc, there's no other way around it. But that's only the groupID in the pom.xml right? Something, similar to the ical4j library, I am guessing, where the groupID is org.mnode.ical4j, but the library still maintains, net.fortuna.ical4j, in the jar. I guess, we can name it something along those lines of com.github.caldav4j.

Perhaps, com.osaf.caldav4j? Is that allowed? or maybe something else.

**Comment by ioggstream** [comment]
Theoretically it should be a fqdn you own: this excludes osaf.org ;)

Good candidates are:

 -  io.github.caldav4j
 - com.github.caldav4j

Feedback from other projects is welcome.

Peace,
R.

**Comment by TheAntimist** [comment]
@ioggstream They seem alright. If you wish to proceed with either of those, feel free to do so.

**Comment by useratgit** [comment]
We've been using caldav4j artifact from https://caldav4j.googlecode.com/svn/maven/ and it is no longer accessible from there. Is this artifact going to be made available in central maven repository? If so, how long it is going to take?

Thanks!

**Comment by ioggstream** [comment]
@useratgit we're working on the maven central stuff. Can you please try setting this url into your pom.xml?  https://raw.github.com/caldav4j/maven/master/repo

**Comment by TheAntimist** [comment]
@ioggstream Just a note that, url gives a 404.

**Comment by useratgit** [comment]
@ioggstream Thanks a lot! Our builds are working now with the given URL :)

**Comment by ioggstream** [comment]
@useratgit stay tuned, as I hope soon to publish everything on maven central under
 
 - groupId:  com.github.caldav4j

**Comment by jameswennmacher** [comment]
@ioggstream getting the artifact(s) into maven central would be great.  Thank you.  The uPortal project just tripped on not being able to find the caldav4j artifact also (we use the 0.7 release).  Looks like slide/* dependencies are also not present in maven central.

**Comment by ioggstream** [comment]
@jameswennmacher I should finish that this week, sorry for the delays.

**Comment by ioggstream** [comment]
@jameswennmacher @useratgit  I uploaded the 0.8-SNAPSHOT to maven central: let me know if that works for you.

The slide library is now embedded in the caldav4j sources as managing further repos requires rebuilding the slide jars, which I don't want.

Let me know,
R.

**Comment by jameswennmacher** [comment]
@ioggstream I was a bit busy at work getting ready for a conference this week (of course really getting things done because I'll be out for a week.  The conference prep occurred on the airplane ride here :smile: ). I hope to have a chance to look at this sometime this week.

**Comment by ioggstream** [comment]
@jameswennmacher no pbm.

**Comment by drewwills** [comment]
Is there any progress on this issue?  It continues to trouble us (Apereo uPortal).

We're looking for a non-SNAPHOT build.  I'm sure we can upgrade to the 0.8 version, if necessary.

**Comment by jameswennmacher** [comment]
@drewwills we need to test out the 0.8 snapshot version.  If it works for us, I was going to ask that he publish a 0.8-M1 or similar official version to Maven Central.

**Comment by ioggstream** [comment]
@drewwills  @jameswennmacher I uploaded the 0.8-SNAPSHOT to maven central: let me know if that works for you.

You need to switch to 0.8 anyway because 0.7 depends on old, unavailable, Ehcache packages.

If the 0.8 works then I'll move it to release.

Peace,
R.

**Comment by ioggstream** [comment]
@drewwills @jameswennmacher are you related with bedework? I just created a docker image to test the new jcr-dev branch based on jackrabbit.

**Comment by felsenhower** [comment]
Is there any progress on this?

Maven central cannot find com.github.caldav4j.

Using the github maven repository like the following fails with similar messages as in [this jitpack.io log](https://jitpack.io/com/github/caldav4j/caldav4j/0.7/build.log):
```
 <repositories>
  <repository>
   <id>com.github.caldav4j</id>
   <url>https://raw.githubusercontent.com/caldav4j/maven/master/repo/</url>
  </repository>
 </repositories>
...
 <dependencies>
  <dependency>
   <groupId>com.github.caldav4j</groupId>
   <artifactId>caldav4j</artifactId>
   <version>0.7</version>
  </dependency>
  <dependency>
   <groupId>com.github.caldav4j</groupId>
   <artifactId>jakarta-slide-webdavlib</artifactId>
   <version>2.2pre1-httpclient-3.0</version>
  </dependency>
 </dependencies>
```

The only thing that seems to work is using jitpack.io on commit 8d6d7c758004f2f0986c4e2a7476541e34a8db10 as specified [here](https://jitpack.io/#caldav4j/caldav4j/8d6d7c7580).

**Comment by TheAntimist** [comment]
@felsenhower Is it possible for you to use the 0.9 Snapshot, version. Currently it's under development but it should be fine in most cases. It's available on Sonatype you can do it like this:

<repository>
            <id>sonatype-snapshots</id>
            <name>Sonatype Snapshots Repository</name>
<url>http://oss.sonatype.org/content/repositories/snapshots/</url>
<releases><enabled>false</enabled></releases>
<snapshots><enabled>true</enabled></snapshots>
        </repository>

Apologies for the formatting, on phone right now.

**Comment by ioggstream** [comment]
caldav4j requires proper javadoc to be promoted from snapshot to release.

**Comment by TheAntimist** [comment]
Yeah, I realize just that, while running a couple of those tests, I noticed
that oddity. Anyway, I'll get to it.

**Comment by TheAntimist** [comment]
And done.
