### ISSUE TITLE
Invalid redirect location

### ISSUE THREAD

**Issue by meistersoda** [caldav4j/caldav4j#57]
Hi,

on several servers I get an org.apache.commons.httpclient.InvalidRedirectLocationException when the redirect path contains spaces. Any ideas on how to avoid / fix this?

Using HTTPClient 4.1 would be an option, but the caldav4j jar comes with 3.1

Thank you,
Tim

**Comment by ioggstream** [comment]
Hi @meistersoda,

I'm actually focused maintaining a large delivery based on httpclient 3.1.

If  you can provide a patch to support httpclient4 I'm willing to help. 

The main issue is related to the Slide-webdav library not supporting httpclient4. Though old, Slide has a nice support for ACL, that's something missing in newer webdav libraries...

Let me know,
R.

**Comment by ioggstream** [comment]
@meistersoda you can try the jcr-dev branch which is based on jackrabbit.

**Comment by TheAntimist** [comment]
@ioggstream @meistersoda WIth regard to HC4, right now, since jackrabbit hasn't completed the migration to HC4 yet, we will have to wait it out until then. The jackrabbit issue here: https://issues.apache.org/jira/browse/JCR-2406
