### ISSUE TITLE
Fix CalDAVCalendarCollectionWithCacheTest.testGetEventResources

### ISSUE THREAD

**Issue by TheAntimist** [caldav4j/caldav4j#58]
As mentioned earlier, We get a Assertion Error in two places one is on: 

Note: This test produces a calendar-query, for the timerange 1-9 Jan. Whose calendar responses are then stored in `l`.

```
        for (Calendar calendar : l) {
        ComponentList vevents = calendar.getComponents().getComponents(
                Component.VEVENT);
        VEvent ve = (VEvent) vevents.get(0);
        String uid = ICalendarUtils.getUIDValue(ve);
        int correctNumberOfEvents = -1;
        if (ICS_DAILY_NY_5PM_UID.equals(uid)) {
            // one for each day
            correctNumberOfEvents = 1;
        } else if (ICS_ALL_DAY_JAN1_UID.equals(uid)) {
            correctNumberOfEvents = 1;
        } else if (ICS_NORMAL_PACIFIC_1PM_UID.equals(uid)) {
            correctNumberOfEvents = 1;
        } else if (ICS_FLOATING_JAN2_7PM_UID.equals(uid)) {
            correctNumberOfEvents = 0;
        } else {
            fail(uid
                    + " is not the uid of any event that should have been returned");
        }

        assertEquals(correctNumberOfEvents, vevents.size());
    }
```

Specifically, in line: 

```
        } else if (ICS_FLOATING_JAN2_7PM_UID.equals(uid)) {
            correctNumberOfEvents = 0;
```

Since the event, ICS_FLOATING_JAN2_7PM, uses a Floating timezone, this, depending on the timezone sets `correctNumberOfEvents` to 0, and the `l.size()` to 4. Thus, causing the assertion to fail at:

```
 231:           assertEquals(correctNumberOfEvents, vevents.size());
```

comes as `(0, 1)`. And at line:

```
    // 3 calendars - one for each resource (not including expanded
    // recurrences)
 236:    assertEquals(3, l.size());
```

as stated earlier, `l.size()` comes up as 4, thus causing this to fail as well. What do you propose for this specific Test?

**Comment by TheAntimist** [comment]
@ioggstream This test might become obsolete if CalDAVCalendarCollection is removed.

**Comment by ioggstream** [comment]
Yes, drop it.

**Comment by TheAntimist** [comment]
Closing this issue, since CalDAVCalendarCollection is removed and this test succeeds on Baikal under CalDAVCollectionTest.
