### ISSUE TITLE
JCR-WebDAV migration: mkticket 

### ISSUE THREAD

**Issue by ioggstream** [caldav4j/caldav4j#60]
@TheAntimist 

> With respect to PropFindMethod, I want to ask, why has the whole class overridden, just for
>  ticketdiscovery?

Ticket methods are entirely different from the other caldav stuff

> Including a whole initResponseHashtable, function? 

Yes, it sucks. Don't know why the specs were that way

> I am wondering on how to proceed in this case, I could simply just override and DavMethodBase, and the except for a couple of a things most of the reponses and rest would use the jcr classes.

If you don't require caldav tickets you can just lower the priority of that ticket.

**Comment by TheAntimist** [comment]
@ioggstream Thanks for the response.

Oddly enough, both the MKTICKET and DELTICKET, were fairly easy to migrate, and have been tested to work on DaviCal. Only PropFind, is the one that remains, which is what I have trouble migrating.

**Comment by TheAntimist** [comment]
@ioggstream This, should now work with my jackrabbit branch. Having tested it.

**Comment by ioggstream** [comment]
Looking forward to test everything this week.

**Comment by TheAntimist** [comment]
@ioggstream Remember to use the [jcr-dev](https://github.com/TheAntimist/caldav4j/tree/jcr-dev) branch for testing, since that's the branch I use for Jackrabbit migration, after you specified. Haven't merged from a PR yet, but should happen soon.

**Comment by ioggstream** [comment]
Ok.

These days I'm quite busy with some medical stuff :( I'll play that asap.

Thx for all your essential work!

R.

**Comment by TheAntimist** [comment]
No problems, just let me know when you are done with it. Health comes first anyway.

**Comment by TheAntimist** [comment]
@ioggstream Just letting you know that I added support for Delete Method with ETags, the commit can be found here: https://github.com/TheAntimist/caldav4j/commit/064e2bdb0ee6628cc920a9649378a3454242c418#diff-2f76b756fd5013a38ee34364bff97ee8R25

**Comment by TheAntimist** [comment]
@ioggstream Any updates on the testing?

**Comment by TheAntimist** [comment]
@ioggstream Haven't heard from you with regard to the testing. I hope you can make this faster

But in any case. I have just now updated the jcr-dev branch with updates to CalDAVCollection, by removing all references to Google Tombstones, and now, all the Methods, perform a releaseConnection after executing, this is helpful if you use a MultiThreadedConnectionManager. Refer to commit here: d5ed3ba065be1fdc7564aa2099db518b42b83eb6

I hope to hear more from you with regard to the testing.

**Comment by ioggstream** [comment]
As of now I have:

```
Failed tests:   
  queryPartialCalendar(org.osaf.caldav4j.methods.NewCalDAVReportTest): expected:<3> but was:<0>
  queryCalendar(org.osaf.caldav4j.CalDAVCollectionTest)
  testGetEventResources(org.osaf.caldav4j.CalDAVCollectionTest): expected:<3> but was:<2>
  testAddNewRemove(org.osaf.caldav4j.CalDAVCollectionTest)
  testGetWithoutCacheThenWithCache(org.osaf.caldav4j.CalDAVCollectionTest)
```

**Comment by ioggstream** [comment]
@TheAntimist I'm testing with this bedework image https://hub.docker.com/r/ioggstream/bedework/

**Comment by TheAntimist** [comment]
@ioggstream I just had those working on DAViCal, perhaps a small change in the server causes the tests to fail. I'll try to fix it today.

**Comment by TheAntimist** [comment]
@ioggstream Got the docker image and tested, but was only able to fix testGetEventResources, mostly, because I used to have cases, where I would get either 2 or 3 events returned, in multiple tests. Added a delay of one second, and that seemed to solve it for bedework. The commit is here: bb5935a

As to the rest, they fail for the reasons specified - 
 * queryPartialCalendar - No expansion of events occured during this test by bedework, i.e. ignores the calendar-expand option.
* queryCalendar, testAddNewRemove, testGetWithoutCacheThenWithCache - For some reason the Text-Match does not return anything in the MultiStatus Response. While trying it independently, I get a Internal Server Error, hence causing me to assume it's a Bedework thing.

**Comment by ioggstream** [comment]
@TheAntimist if everything is fine to you then it's good ;)

 - I'll open the tickets on bedework;
 - I'll try to build a SabreDAV image.

On my davical instance all ACL tests were in error, so I tried bedework...

Anyway all your branch is merged on caldav4j:jcr-dev.

PS: are we connected via linkedin, right?

**Comment by TheAntimist** [comment]
@ioggstream Good to hear, about the SabreDAV. I'll test it after it's up.

About LinkedIn, I'm afraid, not, since, I don't have a account, lots of people telling me about it. I'll get it done this week, if possible.

**Comment by ioggstream** [comment]
2016-07-06 18:04 GMT+02:00 Ankush Mishra <notifications@github.com>:

> About LinkedIn, I'm afraid, not,
>

So the Ankush Mishra I'm connected with is not you :DDD

In case let me know and I'll add you to the linkedin caldav4j project  ;)

Peace,
R.

**Comment by TheAntimist** [comment]
@ioggstream Haha, well, yeah alright with me.

Also, I just pushed an update to the jcr-dev with an updated version of iCal4j, currently at 2.0-beta1: a4b5968c23081752946d5d4337f56672449ee4e4

**Comment by TheAntimist** [comment]
Closing this issue, because this complete, and mkticket is now deprecated.
