### ISSUE TITLE
Change ehcache constructor using between ehcache-1.1 and ehcache-1.2

### ISSUE THREAD

**Issue by ioggstream** [caldav4j/caldav4j#61]
Running 
```
mvn clean package -Dmaven.test=**CalDAVCalendarCollectionWithCacheTest
```

Results in the following warning.

```
WARN - Cache.<init>(456) | An API change between ehcache-1.1 and ehcache-1.2 results in the persistence path being set to /tmp when the ehcache-1.1 constructor is used. Please change to the 1.2 constructor.
```

**Comment by TheAntimist** [comment]
@ioggstream Just noticed that a while back this stopped coming up for me. I am still using 2.10.2 ehcache.

**Comment by TheAntimist** [comment]
@ioggstream Ignore my previous comment. Just got it again.

**Comment by TheAntimist** [comment]
@ioggstream Updated my repo with a fix for this, i.e. shifted the ehcache constructor from v1.1 to v1.2

Please see: https://github.com/TheAntimist/caldav4j/commit/5a4e211ec07d4bce027b840fc8ae9dfbbf63386b#diff-e07d94dbfc2ba2da883e28e48fee2f33R41

**Comment by ioggstream** [comment]
Merged into jcr-dev
