### ISSUE TITLE
JCR Migration: Test ThreadLocal for memory issues.

### ISSUE THREAD

**Issue by TheAntimist** [caldav4j/caldav4j#62]
I found out, that using `ThreadLocal<CalendarBuilder>` in `CalDAV4JMethodFactory` causes a memory leak in a Java WebApplication like a .war running under Tomcat. Read more about it here: http://javarevisited.blogspot.in/2013/01/threadlocal-memory-leak-in-java-web.html

Any way to address this issue? Do we have to address this issue?

**Comment by ioggstream** [comment]
iirc the ThreadLocal is associated to object factories (Eg. you should just have one instance of that class)

eg.
```
factory =  getMethodFactory();  // just one calendarBuilder
```
Does it sound right to you?

Let me know + Peace,
R:

PS: I never noticed JBoss / Tomcat memory issues on hosted caldav4j apps, but if you (or your colleagues) noticed one, please let me know. 

You can use jstack|jmap|jconsole to count the calendarBuilder instances on a long running server.

**Comment by TheAntimist** [comment]
@ioggstream it's actually been a while since, I even noticed it. But from what you say it does sound right. Last time, I just wasn't sure if that was the case that we ensured only one instance. In any case, thanks for the clarification.

Should I close this minor issue then?

**Comment by ioggstream** [comment]
If you found a memory leak:

 - leave it as is and add details about the leak

If you didn't found a memory leak but you are afraid of ThreadLocal:

  - rename the ticket as "test ThreadLocal for memory issues" 
  - link the exact code line 

If @markhobson has some time, he can just check if it's fine or not in a couple of minutes ;)

**Comment by TheAntimist** [comment]
@ioggstream Well since, I don't recall, I changed the title. And here's the trap instances to be reviewed:
https://github.com/caldav4j/caldav4j/blob/jcr-dev/src/main/java/org/osaf/caldav4j/model/response/CalendarDataProperty.java#L41
https://github.com/caldav4j/caldav4j/blob/jcr-dev/src/main/java/org/osaf/caldav4j/methods/CalDAV4JMethodFactory.java#L34

**Comment by TheAntimist** [comment]
Closing, because non reproducible. Also, fixed the CalendarData instance through the addition of a setter.
