### ISSUE TITLE
not work get by uid for caldav.yandex.ru

### ISSUE THREAD

**Issue by peterarsentev** [caldav4j/caldav4j#65]
When I try to get an event by uid. I have the exception.

I created an event by caldav4j. Here everything is ok.

BEGIN:VEVENT
DTSTAMP:20171205T082157Z
DTSTART:20170607T000000Z
DTEND:20171210T000000Z
SUMMARY: Test for update
UID:20171205T112157-4dc18613-7e2d-46fb-b9da-b0a17298a9c2-support@job4j.ru
END:VEVENT

Then I want to get this event by id and update it.

2017/12/05 11:21:58:687 MSK [DEBUG] header - >> "Content-Type: text/xml[\r][\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] header - >> "[\r][\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] content - >> "<?xml version="1.0"?>[\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] content - >> "<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav">[\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] content - >> "    <D:prop xmlns:D="DAV:">[\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] content - >> "        <D:getetag/>[\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] content - >> "        <C:calendar-data/>[\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] content - >> "    </D:prop>[\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] content - >> "    <C:filter>[\n]"
2017/12/05 11:21:58:688 MSK [DEBUG] content - >> "        <C:comp-filter name="VCALENDAR">[\n]"
2017/12/05 11:21:58:691 MSK [DEBUG] content - >> "            <C:comp-filter name="VEVENT">[\n]"
2017/12/05 11:21:58:691 MSK [DEBUG] content - >> "                <C:prop-filter name="UID">[\n]"
2017/12/05 11:21:58:691 MSK [DEBUG] content - >> "                    <C:text-match collation="i;ascii-casemap">20171205T112157-4dc18613-7e2d-46fb-b9da-b0a17298a9c2-support@job4j.ru</C:text-match>[\n]"
2017/12/05 11:21:58:691 MSK [DEBUG] content - >> "                </C:prop-filter>[\n]"
2017/12/05 11:21:58:691 MSK [DEBUG] content - >> "            </C:comp-filter>[\n]"
2017/12/05 11:21:58:691 MSK [DEBUG] content - >> "        </C:comp-filter>[\n]"
2017/12/05 11:21:58:691 MSK [DEBUG] content - >> "    </C:filter>[\n]"
2017/12/05 11:21:58:691 MSK [DEBUG] content - >> "</C:calendar-query>[\n]"
2017/12/05 11:21:58:730 MSK [DEBUG] header - << "HTTP/1.1 404 Not Found[\r][\n]"
2017/12/05 11:21:58:731 MSK [DEBUG] header - << "HTTP/1.1 404 Not Found[\r][\n]"
2017/12/05 11:21:58:731 MSK [DEBUG] header - << "Server: nginx[\r][\n]"
2017/12/05 11:21:58:731 MSK [DEBUG] header - << "Date: Tue, 05 Dec 2017 09:21:59 GMT[\r][\n]"
2017/12/05 11:21:58:731 MSK [DEBUG] header - << "Content-Length: 0[\r][\n]"
2017/12/05 11:21:58:731 MSK [DEBUG] header - << "Connection: keep-alive[\r][\n]"
2017/12/05 11:21:58:731 MSK [DEBUG] header - << "X-Request-Id: cf2pAKWd_1o[\r][\n]"

And then I see. 

org.osaf.caldav4j.exceptions.ResourceNotFoundException: Could not find resource for the UID '20171205T112157-4dc18613-7e2d-46fb-b9da-b0a17298a9c2-support@job4j.ru'

I guess, it maybe connect to some changes in caldev.yandex.ru api.

**Comment by TheAntimist** [comment]
According to the RFC 4791, it's supposed to return a response XML as well. Here's the lines from the RFC:
>For instance, a request to retrieve the value of a property that does not exist is an error and MUST be noted with a response XML element that contains a 404 (Not Found) status value.

But regardless, it seems to me as a server issue. Since, the implementations vary.

**Comment by peterarsentev** [comment]
Thanks for answers. Yandex Calendar does not support a prop-filter. 

You can close this issue.
