### ISSUE TITLE
javadoc for CalDAVCollection.java

### ISSUE THREAD

**Issue by ioggstream** [caldav4j/caldav4j#67]
- add missing javadoc
- fix malformed html and/or skip those errors

```
[ERROR] /home/rpolli/workspace-luna/caldav4j/src/main/java/org/osaf/caldav4j/model/request/Comp.java:35: error: malformed HTML
[ERROR] * <!ELEMENT allprop EMPTY>
[ERROR] ^

```

**Comment by TheAntimist** [comment]
I'll add it in over the weekend, thought, I'd covered most of it, oh well.

**Comment by ioggstream** [comment]
I added some more with sed ;) pull the latest master.

I added some personal infos required by sonatype to the pom.xml. You can add yours too :D

**Comment by TheAntimist** [comment]
All right, will do. And regarding the malformed ones, I fixed some, it was due to have the RFC as plain text, as shown instead of `&lt;!ELEMENT&gt;`
