### ISSUE TITLE
enhancement: investigate warning at build time

### ISSUE THREAD

**Issue by ioggstream** [caldav4j/caldav4j#69]
Investigate warning at compile time:

- https://travis-ci.org/caldav4j/caldav4j/jobs/336952858#L985

- https://travis-ci.org/caldav4j/caldav4j/jobs/336952858#L997

Recompile with -Xlint:unchecked for details.

**Comment by TheAntimist** [comment]
Probably a type casting issue, I'll look into it. I recall them from DefaulDavProperty TypeCasts, which were from Apache Jackrabbit

**Comment by TheAntimist** [comment]
Okay, I got time to investigate, the issues are:

 - Deprecation of Tickets, gave the first warning
 - Second, was due to a type casting of iCal4j components. Nothing to be concerned about, as far as I see.
