### ISSUE TITLE
Fix Readme

### ISSUE THREAD

**Issue by TheAntimist** [caldav4j/caldav4j#70]
The following has to be performed on the README:

 * Add Maven central details - https://oss.sonatype.org
 * Add Travis CI banners #76 
 * Streamline, order of headings
 * Update to reflect current status of the project (JCR, Ticket deprecation)
 * Add examples?

**Comment by enummela** [comment]
Proposed fix for README.md: #73.

**Comment by TheAntimist** [comment]
It's not complete, but I'm willing to merge it as is.

**Comment by ioggstream** [comment]
LGTM.

Go @TheAntimist !

**Comment by TheAntimist** [comment]
And merged, thanks for everything @enummela
