### ISSUE TITLE
Change the class structure from org.osaf to com.github?

### ISSUE THREAD

**Issue by TheAntimist** [caldav4j/caldav4j#71]
Just wondering, if we should now that osaf is a thing of the past? Perhaps, have a final release with org.osaf, and then transition to com.github?

@ioggstream thoughts?

**Comment by ioggstream** [comment]
Agree. Plan for the 1.0release?

R

Il 04 feb 2018 8:08 AM, "Ankush Mishra" <notifications@github.com> ha
scritto:

**Comment by TheAntimist** [comment]
Sounds fine to me. Just to add, I also need to update the copyright numbers.
