### ISSUE TITLE
Update Java version & iCal4j

### ISSUE THREAD

**Issue by TheAntimist** [caldav4j/caldav4j#79]
The [new iCal4j versions](https://github.com/ical4j/ical4j#setup), require Java 8, or Java 7 based on the version used. I think a need for an update is needed at hand.

**Comment by ioggstream** [comment]
Ok for removing j6 starting from 1.0.

If there are security issues in ical4j we bump to 1.0 and shift http4 to
1.1.

Let's use semver.org

Il mer 1 ago 2018, 11:26 Ankush Mishra <notifications@github.com> ha
scritto:

**Comment by TheAntimist** [comment]
No security issues as far as I see in the [release notes](https://ical4j.github.io/docs/ical4j/release-notes.html) probably just a java update for cleaner code.

Agreed on all points, though, since no security updates to ical4j, http4 is still on track for 1.0.

**Comment by TheAntimist** [comment]
Now that, testing of everything is done. Can I start migration of iCal4j?

**Comment by ioggstream** [comment]
To clarify, 

  - v1 will have both: java7+, http4, ical4j3

Right?

**Comment by TheAntimist** [comment]
Yes, that's the plan.

**Comment by TheAntimist** [comment]
To add, #71 fix will also be included, for the change from org.osaf to com.github.
