### ISSUE TITLE
Mocked Caldav services for testing

### ISSUE THREAD

**Issue by TheAntimist** [caldav4j/caldav4j#80]
I was thinking of shifting the testing from an actual server to a mocked httpclient implementation, providing a standardized way to test them without an external environment dependency, while still maintaining tests during build. As of now, we can't test unless we have an external server to test it on.

We could use something like [Mockito.](http://site.mockito.org/)

@ioggstream thoughts?

**Comment by ioggstream** [comment]
I prefer to avoid mocks because for caldav4j they proved to be:

  - hard to maintain
  - give a false confidence, as people won't test against their implementation

A viable solution would be using a CI based with 2  containers, one of which running a caldav server.

**Comment by TheAntimist** [comment]
Well, if it's hard to maintain, then no point in having it, because I was hoping they'd be easier to maintain. Though, having two containers sounds feasible. I guess we'll been that bridge a bit later.
