### ISSUE TITLE
Dockerized Baikal for automated tests

### ISSUE THREAD

**Issue by TheAntimist** [caldav4j/caldav4j#85]
## I expect

Travis CI to run automated tests on Baikal

## Instead

No testing on CI.

## Notes

Baikal official provides the following notes for a dockerized install: http://sabre.io/baikal/docker-install/

There's also this repo here, which could work: https://github.com/ckulka/baikal-docker

Should we go ahead?

**Comment by ioggstream** [comment]
I wanted to move from Travis to circleci. Circleci has a command that runs the tests on local docker machine.

Google for circleci-local.

It is fine for Baikal and there are sogo free accounts we can use for testing.

**Comment by ioggstream** [comment]
Merged in #96
