### ISSUE TITLE
Refactor UID generator code

### ISSUE THREAD

**Issue by ioggstream** [caldav4j/caldav4j#87]
## Reproduce

  - caldav4j version or commit: 4e69fcacd788a4
  - server name: NA
  - code
 https://github.com/caldav4j/caldav4j/blame/4e69fcacd788a41e0255e64b5df2cc34f933b7b5/src/main/java/org/osaf/caldav4j/CalDAVCollection.java#L370

```
			// TODO move all these lines into ICalendarUtils
			uid = ICalendarUtils.getUIDValue(c);		
			if (uid == null) {
				uid = random.nextLong() + "-" + random.nextLong();
				ICalendarUtils.setUIDValue(c, uid);
			}

```

## I expect

This to be in ICalendarUtils and using UUID

## Instead

generates an UID using two random numbers

## Notes

The reason could be some old caldav server not supporting UUID but now should be gone.

**Comment by signalarun** [comment]
OK
