### ISSUE TITLE
Assigning time some slots and making rest of slots unavailable with caldav for a user

### ISSUE THREAD

**Issue by signalarun** [caldav4j/caldav4j#90]
Before submitting an issue, [read the FAQ](https://github.com/caldav4j/caldav4j/wiki/FAQ.md)
then describe the issue using the following template

## Reproduce

Steps to reproduce the issue:

  - caldav4j version 0.9.1
  - server name SOGO

## I wish

  I am trying to build an appoinment application with caldav server. 

For that some slots need to be free for a service provider and the rest of the slots need to be not available for slot. Is it possible to do that with caldav4j or caldav.

## Notes

Further notes you want to attach

**Comment by TheAntimist** [comment]
If you mean that the calendar should have the "Show as: Free" or "Show as: Busy", that's specific to how your server handles the displaying. But it's a part of the iCalendar. So, here's a snippet:

```icalendar
BEGIN:VEVENT
DTEND:20181025T080000Z
DTSTAMP:20181025T052636Z
DTSTART:20181025T073000Z
SEQUENCE:0
SUMMARY;LANGUAGE=en-in:Busy
TRANSP:OPAQUE
UID:randomUID
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
END:VEVENT
```

This is generated by Outlook, where it stores the Free/Busy data in a `X-MICROSOFT-CDO-BUSYSTATUS` property. Non-standard, but if you want to have some standard setting refer to, [iCalendar Specification RFC 5545 Section 3.2.9](https://tools.ietf.org/html/rfc5545#section-3.2.9), which states to use a `FBTYPE` property for standardization.

For example:

```icalendar
FBTYPE:FREE
```

**Comment by ioggstream** [comment]
@signalarun 

Afaik there's no way of knowing that unless people pre-fills their own calendar.

if your server supports rfc7953, you can file a ticket for the implementation though.

**Comment by TheAntimist** [comment]
As @ioggstream , I was under assumption that users already have their data, or want to set the data. RFC7953, could work, but it depends on the server.

**Comment by TheAntimist** [comment]
Closing this issue due to no further activity.
