### ISSUE TITLE
publish rc2 version in the maven repository

### ISSUE THREAD

**Issue by teymourlouie** [caldav4j/caldav4j#93]
@ioggstream @TheAntimist I need to use the fix in PR #92 in my project.
Would you please build a new version v1.0.0-rc.2?

All the best, 
Teymourlouie

**Comment by TheAntimist** [comment]
@ioggstream Your call on this one.

**Comment by ioggstream** [comment]
@TheAntimist thanks in the meanwhile. I wanted to CI the snapshot build :)

**Comment by TheAntimist** [comment]
@teymourlouie This has been fixed and the release should pop up on maven soon.

**Comment by teymourlouie** [comment]
@TheAntimist  @ioggstream  Thanks so much.
